---
- name: Setup Workstation
  hosts: localhost
  become: true
  gather_facts: true

  vars_files:
    - vars.yml

  tasks:
    - include_tasks: tasks/yum-repos.yml
    - include_tasks: tasks/dnf.yml
    - include_tasks: tasks/snap.yml