---
- include_vars: vars.yml
- name: Add multiple yum repos with gpgkey
  yum_repository:
    name: '{{ item.repo }}'
    http_caching: packages
    gpgcheck: yes
    description: '{{ item.description }}'
    state: present
    baseurl: '{{ item.baseurl }}'
    enabled: yes
    repo_gpgcheck: yes
    gpgkey: '{{ item.gpgkey }}'
  with_items: '{{ yum_repos }}'